// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSoZHTC9GsiyJZfc1LWoEVrq_iba43q-g',
    appId: '1:599023505640:web:a5e37b0c93133b460a395d',
    messagingSenderId: '599023505640',
    projectId: 'pakshu-608ed',
    authDomain: 'pakshu-608ed.firebaseapp.com',
    storageBucket: 'pakshu-608ed.firebasestorage.app',
    measurementId: 'G-Z23QTCY4GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR2jrZhXx20XcUlF4r_ApysITAKuWDkd0',
    appId: '1:599023505640:android:03369dc297f3c1c30a395d',
    messagingSenderId: '599023505640',
    projectId: 'pakshu-608ed',
    storageBucket: 'pakshu-608ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnKc8cFQ-WuxMknerFk2trwge8IPAtY1U',
    appId: '1:599023505640:ios:f7cf655895dec56c0a395d',
    messagingSenderId: '599023505640',
    projectId: 'pakshu-608ed',
    storageBucket: 'pakshu-608ed.firebasestorage.app',
    iosBundleId: 'com.example.pakshu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnKc8cFQ-WuxMknerFk2trwge8IPAtY1U',
    appId: '1:599023505640:ios:f7cf655895dec56c0a395d',
    messagingSenderId: '599023505640',
    projectId: 'pakshu-608ed',
    storageBucket: 'pakshu-608ed.firebasestorage.app',
    iosBundleId: 'com.example.pakshu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSoZHTC9GsiyJZfc1LWoEVrq_iba43q-g',
    appId: '1:599023505640:web:56d5e2d38d6d55c00a395d',
    messagingSenderId: '599023505640',
    projectId: 'pakshu-608ed',
    authDomain: 'pakshu-608ed.firebaseapp.com',
    storageBucket: 'pakshu-608ed.firebasestorage.app',
    measurementId: 'G-XLSF9TM4KR',
  );

}